title: Mikail Stewart
description: Mikail Stewart — 明凯, Princeton CS ’27.
author: Mikail Stewart
email: ms3554@princeton.edu
baseurl: ""
url: "https://MingkaiBuilds.github.io"

markdown: kramdown
highlighter: rouge
permalink: pretty

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
