title: Mikail Stewart
description: Research on Computational Identity Continuity
author: Mikail Stewart
email: ms3554@princeton.edu
baseurl: ""
url: "https://MingkaiBuilds.github.io"

markdown: kramdown
highlighter: rouge
permalink: pretty

collections:
  memos:
    output: true
    permalink: /memos/:name/
  field_notes:
    output: true
    permalink: /field-notes/:name/

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
